apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ansible-playbook-example
  description: "Ansible playbook for deploying X service"
  tags:
    - ansible
    - deployment
  labels:
    backstage.io/kubernetes-id: ansible-playbook-example
  annotations:
    backstage.io/kubernetes-id: ansible-playbook-example
    backstage.io/kubernetes-namespace: ansible-playbook-example
    janus-idp.io/tekton : ansible-playbook-example
    backstage.io/kubernetes-label-selector: 'app=my-app,component=front-end'
spec:
  type: service
  lifecycle: experimental
  owner: x-team
  definition: A repository containing Ansible playbook for deploying X service
