---

- name: Converge
  hosts: server:agent
  tags: always
  tasks:
    - name: Set Tailscale IP address
      ansible.builtin.command:
        cmd: tailscale ip -4
      register: tailscale_ip

    - name: Grab Tailscale Status
      ansible.builtin.command:
        cmd: tailscale status --json
      register: tailscale_status

    - name: Parse JSON from tailscale_status
      ansible.builtin.set_fact:
        tailscale_tag: "{{ (tailscale_status.stdout | from_json)['Self']['Tags'][0] | regex_replace('^tag:\\s*', '') }}"


- name: Converge
  hosts: localhost
  tags: always
  tasks:
    - name: Add tailscale IP to inventory
      add_host:
        name: "{{ hostvars[item].tailscale_ip.stdout }}"
        groups: tailscale_hosts
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
        ansible_user: 'admin'
        ansible_ssh_pass: 'admin'
        ansible_become_pass: 'admin'
        tailscale_tag: "{{ hostvars[item].tailscale_tag }}"
      loop: "{{ groups['server'] + groups['agent'] }}"
      when: hostvars[item].tailscale_ip.stdout is defined and hostvars[item].tailscale_tag is defined
      changed_when: False

- name: Converge
  hosts: tailscale_hosts
  vars:
    molecule_is_test: true
    k3s_become: true
    k3s_release_version: "v1.25.11+k3s1"
    k3s_etcd_datastore: true
    k3s_use_experimental: true
    vpn_auth: "{{ 'name=tailscale,joinKey=' + lookup('ansible.builtin.env', 'TAILSCALE_VPN_AUTH') }}"
    client_id: "{{ lookup('ansible.builtin.env', 'TAILSCALE_CLIENT_ID') }}"
    client_secret: "{{ lookup('ansible.builtin.env', 'TAILSCALE_CLIENT_SECRET') }}"
    k3s_server_manifests_templates:
      - "templates/operator.yml.j2"
      - "templates/authproxy-rbac.yml.j2"
      - "templates/proxy.yml.j2"
      - "templates/userspace-proxy.yml.j2"
    k3s_server:
      secrets-encryption: true
      write-kubeconfig-mode: '0644'
      vpn-auth: "{{ vpn_auth }}"
      disable:
        - servicelb
        - traefik
    k3s_agent:
      vpn-auth: "{{ vpn_auth }}"
  pre_tasks:
    - name: Set each node to be a control node
      ansible.builtin.set_fact:
        k3s_control_node: true
      when: tailscale_tag == 'k3s-server'
  roles:
    - role: xanmanning.k3s

  tasks:
    - name: Check if k3s.yaml exists
      ansible.builtin.stat:
        path: /etc/rancher/k3s/k3s.yaml
      register: k3s_yaml_stat
      tags: kubeconfig

    - name: debug through ansible.env
      debug: var=ansible_user_dir
      tags: kubeconfig

    - name: Ensure .kube directory exists
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      when: k3s_yaml_stat.stat.exists
      tags: kubeconfig

    - name: Move k3s kubeconfig to user's kube directory
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ ansible_user_dir }}/.kube/config"
        remote_src: true
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
      when: k3s_yaml_stat.stat.exists
      tags: kubeconfig

