---

- name: Converge
  hosts: server:agent
  tags: always
  tasks:
    - name: Set Tailscale server IP address
      ansible.builtin.command:
        cmd: tailscale ip -4
      register: tailscale_server_ip
      when: inventory_hostname in groups['server']

    - name: Set Tailscale agent IP address
      ansible.builtin.command:
        cmd: tailscale ip -4
      register: tailscale_agent_ip
      when: inventory_hostname in groups['agent']

- name: Converge
  hosts: localhost
  tags: always
  tasks:
    - name: Add tailscale IP to inventory for both servers and agents
      add_host:
        name: "{{ (hostvars[item].tailscale_server_ip.stdout if item in groups['server'] else hostvars[item].tailscale_agent_ip.stdout) }}"
        groups: tailscale_k3s_hosts
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
        ansible_user: 'admin'
        ansible_ssh_pass: 'admin'
        ansible_become_pass: 'admin'
        k3s_control_node: "{{ item in groups['server'] }}"
      loop: "{{ groups['server'] + groups['agent'] }}"
      when: 
        - "'tailscale_server_ip' in hostvars[item] or 'tailscale_agent_ip' in hostvars[item]"
        - "(item in groups['server'] and hostvars[item].tailscale_server_ip.stdout is defined) or (item in groups['agent'] and hostvars[item].tailscale_agent_ip.stdout is defined)"
      changed_when: False

- name: Converge
  hosts: tailscale_k3s_hosts
  vars:
    molecule_is_test: true
    k3s_become: true
    k3s_release_version: "v1.21"
    k3s_etcd_datastore: true
    k3s_use_experimental: true
    k3s_server:
      secrets-encryption: true
      write-kubeconfig-mode: '0644'
    k3s_agent:
      node-ip: "{{ ansible_default_ipv4.address }}"
  roles:
    - role: xanmanning.k3s

  tasks:
    - name: Check if k3s.yaml exists
      ansible.builtin.stat:
        path: /etc/rancher/k3s/k3s.yaml
      register: k3s_yaml_stat
      tags: kubeconfig

    - name: debug through ansible.env
      debug: var=ansible_user_dir
      tags: kubeconfig

    - name: Ensure .kube directory exists
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      when: k3s_yaml_stat.stat.exists
      tags: kubeconfig

    - name: Move k3s kubeconfig to user's kube directory
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ ansible_user_dir }}/.kube/config"
        remote_src: true
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
      when: k3s_yaml_stat.stat.exists
      tags: kubeconfig

