# - name: Add instance to inventory
#   ansible.builtin.add_host:
#     name: '{{ item.hostname }}'
#     groups: "{{ host_group }}"
#     ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
#   loop: "{{ groups['nodes'] }}"

- name: Use tailscale service
  ansible.builtin.set_fact:
    tailscale_authkey: "{{ lookup('ansible.builtin.env', 'TAILSCALE_KEY') }}"

- name: Set custom up argument for server
  ansible.builtin.set_fact:
    tailscale_args: "--advertise-tags tag:server"
  when: inventory_hostname in groups['server']

- name: Set custom up argument
  ansible.builtin.set_fact:
    tailscale_args: "--advertise-tags tag:agent"
  when: inventory_hostname in groups['agent']

