---

- name: Install Tailscale
  hosts: k3s_cluster
  tasks:
    - name: Use tailscale service
      ansible.builtin.set_fact:
        tailscale_authkey: "{{ lookup('ansible.builtin.env', 'TAILSCALE_KEY') }}"

    - name: Set custom up argument for server
      ansible.builtin.set_fact:
        tailscale_args: "--advertise-tags tag:k3s-server,tag:k3s-cluster"
      when: inventory_hostname in groups['k3s-server']

    - name: Set custom up argument
      ansible.builtin.set_fact:
        tailscale_args: "--advertise-tags tag:k3s-agent,tag:k3s-cluster"
      when: inventory_hostname in groups['k3s-agent']

    - name: Install Tailscale with custom up argument
      ansible.builtin.include_role:
        name: artis3n.tailscale
