---

- name: Prepare
  hosts: all
  tasks:
    - name: Init tailscale credentials variables
      ansible.builtin.include_tasks: ../default/init_tailscale_vars.yml

    - name: Install Tailscale with custom up argument
      ansible.builtin.include_role:
        name: artis3n.tailscale

    - name: Prepare Load Balancer | Ensure HAProxy is installed
      ansible.builtin.package:
        name: haproxy
        state: present
      when: "'loadbalancer' in inventory_hostname"

    - name: Prepare Load Balancer | Ensure HAProxy config directory exists
      ansible.builtin.file:
        path: /usr/local/etc/haproxy
        state: directory
        mode: 0755
      when: "'loadbalancer' in inventory_hostname"

    - name: Prepare Load Balancer | Ensure HAProxy is configured
      ansible.builtin.template:
        src: templates/haproxy-loadbalancer.conf.j2
        dest: /usr/local/etc/haproxy/haproxy.cfg
        mode: 0644
      when: "'loadbalancer' in inventory_hostname"

    - name: Prepare Load Balancer | Ensure HAProxy service is started
      ansible.builtin.command:
        cmd: haproxy -D -f /usr/local/etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid
      args:
        creates: /var/run/haproxy.pid
      when: "'loadbalancer' in inventory_hostname"

