---

- name: Prepare
  hosts: server:agent:loadbalancer
  tags: tailscale_init
  tasks:
    - name: Set custom up argument for server
      ansible.builtin.set_fact:
        tailscale_args: "--advertise-tags=tag:k3s-server"
      when: inventory_hostname in groups['server']

    - name: Set custom up argument
      ansible.builtin.set_fact:
        tailscale_args: "--advertise-tags=tag:k3s-agent"
      when: inventory_hostname in groups['agent']

    - name: Set custom up argument
      ansible.builtin.set_fact:
        tailscale_args: "--advertise-tags=tag:k3s-loadbalancer"
      when: inventory_hostname in groups['loadbalancer']

    - name: Init tailscale credentials variables
      ansible.builtin.include_tasks: ../default/init_tailscale_vars.yml

    - name: Install Tailscale with custom up argument
      ansible.builtin.include_role:
        name: artis3n.tailscale