- name: Delete Linode instances in async
  linode.cloud.instance:
    label: "{{resource_prefix}}-{{item}}"
    state: absent

  # Let's create these instances in async to speed up provisioning times
  async: 120
  poll: 0
  changed_when: false
  loop: "{{ range(0, num_server)|list }}"
  register: instance_job

- name: Wait for all instances to be deleted
  async_status:
    jid: "{{ async_result_item.ansible_job_id }}"
  loop: "{{ instance_job.results }}"
  loop_control:
    loop_var: "async_result_item"
  register: instance_create
  until: instance_create.finished
  retries: 30