---
- name: Converge
  hosts: server:agent
  tasks:
    - name: Set custom up argument for server
      ansible.builtin.set_fact:
        tailscale_args: "--advertise-tags=tag:k3s-server"
      when: inventory_hostname in groups['server']

    - name: Set custom up argument
      ansible.builtin.set_fact:
        tailscale_args: "--advertise-tags=tag:k3s-agent"
      when: inventory_hostname in groups['agent']

    - name: Init tailscale credentials variables
      ansible.builtin.include_tasks: ../default/init_tailscale_vars.yml

    - name: Install Tailscale with custom up argument
      ansible.builtin.include_role:
        name: artis3n.tailscale

    - name: Set Tailscale IP address
      ansible.builtin.command:
        cmd: tailscale ip -4
      register: tailscale_ip

    - name: Grab Tailscale Status
      ansible.builtin.command:
        cmd: tailscale status --json
      register: tailscale_status

    - name: Parse JSON from tailscale_status
      ansible.builtin.set_fact:
        tag: "{{ (tailscale_status.stdout | from_json)['Self']['Tags'][0] | regex_replace('^tag:\\s*', '') }}"

    - name: Debug Tailscale Tag
      debug:
        msg: "Tailscale Tag: {{ tag }}"

    - name: Debug Tailscale IP
      debug:
        msg: "TailScale IP: {{ tailscale_ip.stdout }}"
