---
- name: Uninstall K3s-Cluster
  hosts: k3s-cluster
  become: true
  vars:
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
  roles:
    - role: xanmanning.k3s
      vars:
        k3s_become: true
        k3s_state: uninstalled